In [1]:
import numpy as np
import time

In [2]:
# 1. a) Uniform
uniform = np.random.uniform(0,1,10**6)
u_mean = np.mean(uniform)
u_variance = np.var(uniform)

print 'Uniform Mean: ', u_mean
print 'Uniform Variance: ', u_variance

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1286188173.py, line 6)

In [3]:
# 1. a) Normal
normal = np.random.standard_normal(10**6)
n_mean = np.mean(normal)
n_variance = np.var(normal)

print 'Standard Normal Mean: ', n_mean
print 'Standard Normal Variance: ', n_variance

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (2805400697.py, line 6)

In [4]:
sigma = [[4,1],[1,4]]

In [6]:
# 1. b) Cholesky factorisation

L_cho = np.linalg.cholesky(sigma)
print ('Cholesky Factorisation L: ')
print(L_cho)
Z = [np.random.standard_normal(10**6), np.random.standard_normal(10**6)]
X_cho = np.matmul(L_cho,Z)
print(X_cho)
(X0_mean, X1_mean) = (np.mean(X_cho[0]), np.mean(X_cho[1]))

covariance_cho = np.cov(X_cho[0], X_cho[1])

print('Means: ', X0_mean, ', ', X1_mean)
print('Covariance Matrix: ')
print(covariance_cho)


Cholesky Factorisation L: 
[[2.         0.        ]
 [0.5        1.93649167]]
[[-2.60681321  1.85888382 -0.23338916 ... -4.09470163  0.39032873
   0.35692055]
 [ 1.33497182  1.81180358 -1.83651032 ... -2.10675603 -2.07763906
  -0.44590345]]
Means:  -0.00010357308024116735 ,  4.0955869688506944e-05
Covariance Matrix: 
[[3.99657193 0.99880655]
 [0.99880655 4.00515778]]


In [17]:
# 1. c) PCA factorisation

eigen = np.linalg.eig(sigma)

U = np.transpose(eigen[1])
U_inverse = np.linalg.inv(U)
V = np.matmul(np.matmul(U_inverse, sigma), U)
root_V = np.asmatrix([[V[0][0]**0.5,0], [0,V[1][1]**0.5]])
L_PCA = np.matmul(U, root_V)

print 'PCA Factorisation L:'
print(L_PCA)

X_PCA = np.array(np.matmul(L_PCA, Z))

(X0_mean, X1_mean) = (np.mean(X_PCA[0]), np.mean(X_PCA[1]))

covariance_PCA = np.cov(X_PCA[0],X_PCA[1])

print'Means: ', X0_mean, ', ', X1_mean
print'Covariance Matrix: '
print(covariance_PCA)

PCA Factorisation L:
[[ 1.22474487  1.58113883]
 [-1.22474487  1.58113883]]
Means:  0.001424828312826174 ,  -0.0019708790522887376
Covariance Matrix: 
[[3.99837386 0.99518438]
 [0.99518438 3.99930917]]


In [18]:
# 1. d) Repeat to generate as many pairs as you can generate in 1 min
def generate_pairs():
    pairs = []
    end_time = time.time() + 60
    while(time.time() < end_time):
        Z = [np.random.standard_normal(), np.random.standard_normal()]
        pairs.append(np.array(np.matmul(L_PCA, Z)))
    return len(pairs)

num_pairs = generate_pairs()
print 'Number of pairs generated: ', num_pairs

Number of pairs generated:  7809490
